In [1]:
import sys; sys.path.append('..') # add project root to the python path

In [2]:
from src.common.gridworld import GridworldEnv # Gridworld Environment

In [3]:
num_y, num_x = 4, 4
env = GridworldEnv(shape=[num_y, num_x])

In [4]:
observation_space = env.observation_space
action_space = env.action_space
print("Number of states: {}".format(observation_space))
print("Number of actions: {}".format(action_space))

Number of states: Discrete(16)
Number of actions: Discrete(4)


In [5]:
import numpy as np

In [6]:
num_row = 2
num_col = 2 

rank2_tensor = np.random.random(size=(num_row,num_col))

In [7]:
print(rank2_tensor)

[[0.65420808 0.62134192]
 [0.64673515 0.6899176 ]]


In [8]:
tesor_shape = rank2_tensor.shape
tensor_rank = len(tesor_shape)
print("Tensor shape : {}".format(tesor_shape))
print("Tensor rank : {}".format(tensor_rank))

Tensor shape : (2, 2)
Tensor rank : 2


In [9]:
P = env.P_tensor
print("P shape : {}".format(P.shape))

P shape : (4, 16, 16)


In [10]:
action_up_prob = P[0, :, :]

In [11]:
print(action_up_prob)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [12]:
action_up_prob >= 0

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  Tru

In [13]:
is_greater_than_0 = action_up_prob >= 0
is_all_greater_than_0 = is_greater_than_0.sum() == is_greater_than_0.size

In [14]:
is_all_greater_than_0

True

In [15]:
action_up_prob.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
R = env.R_tensor
print(R)

[[ 0.  0.  0.  0.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]]


In [17]:
_ = env.reset() # Gridworld 초기화
print("Current position index : {}".format(env.s))

Current position index : 11


In [18]:
action_mapper = {
    0: 'UP',
    1: 'RIGHT',
    2: 'DOWN',
    3: 'LEFT'
}

In [19]:
step_counter = 0
while True:      
    print("At t = {}".format(step_counter))
    env._render()
    
    cur_state = env.s
    action = np.random.randint(low=0, high=4)
    next_state, reward, done, info = env.step(action)    
    
    print("state : {}".format(cur_state))
    print("aciton : {}".format(action_mapper[action]))
    print("reward : {}".format(reward))
    print("next state : {} \n".format(next_state))
    step_counter += 1
    if done:
        break

At t = 0
T  o  o  o
o  o  o  o
o  o  o  x
o  o  o  T
state : 11
aciton : UP
reward : -1.0
next state : 7 

At t = 1
T  o  o  o
o  o  o  x
o  o  o  o
o  o  o  T
state : 7
aciton : DOWN
reward : -1.0
next state : 11 

At t = 2
T  o  o  o
o  o  o  o
o  o  o  x
o  o  o  T
state : 11
aciton : RIGHT
reward : -1.0
next state : 11 

At t = 3
T  o  o  o
o  o  o  o
o  o  o  x
o  o  o  T
state : 11
aciton : RIGHT
reward : -1.0
next state : 11 

At t = 4
T  o  o  o
o  o  o  o
o  o  o  x
o  o  o  T
state : 11
aciton : RIGHT
reward : -1.0
next state : 11 

At t = 5
T  o  o  o
o  o  o  o
o  o  o  x
o  o  o  T
state : 11
aciton : LEFT
reward : -1.0
next state : 10 

At t = 6
T  o  o  o
o  o  o  o
o  o  x  o
o  o  o  T
state : 10
aciton : DOWN
reward : -1.0
next state : 14 

At t = 7
T  o  o  o
o  o  o  o
o  o  o  o
o  o  x  T
state : 14
aciton : LEFT
reward : -1.0
next state : 13 

At t = 8
T  o  o  o
o  o  o  o
o  o  o  o
o  x  o  T
state : 13
aciton : DOWN
reward : -1.0
next state : 13 

At t = 9
T 

In [20]:
def run_episode(env, s0):
    _ = env.reset() # Gridworld 를 초기화합니다.
    env.s = s0
    
    step_counter = 0
    while True:
        action = np.random.randint(low=0, high=4)
        next_state, reward, done, info = env.step(action)

        step_counter += 1
        if done:
            break
    return step_counter

In [21]:
n_episodes = 10
s0 = 6

for i in range(n_episodes):
    len_ep = run_episode(env, s0)
    print("Episode {} | Length of episode : {}".format(i, len_ep))

Episode 0 | Length of episode : 4
Episode 1 | Length of episode : 5
Episode 2 | Length of episode : 19
Episode 3 | Length of episode : 5
Episode 4 | Length of episode : 37
Episode 5 | Length of episode : 8
Episode 6 | Length of episode : 7
Episode 7 | Length of episode : 47
Episode 8 | Length of episode : 33
Episode 9 | Length of episode : 15
